Repository SOPT-all/36-COLLABORATION-iOS-CAMPUSPICK, pull requests merged in 2025-05, with the labels that each got.

#7 [Feat] #5 - 동아리 뷰 UI
  36-COLLABORATION-iOS-CAMPUSPICK.xcodeproj/project.pbxproj
  36-COLLABORATION-iOS-CAMPUSPICK/Application/SceneDelegate.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Extensions/UIView+.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Club/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Club/pagination.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Club/pagination.imageset/pagination.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/Model/Enum/CategoryType.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/View/Cell/HeaderCategoryCollectionViewCell.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/View/ClubHeaderView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/View/FindClubView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/View/PopularView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/View/RankingView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/ViewController/ClubViewController.swift
Labels: Feat 💻, 한열 🧄

#10 [Refactor] #9 - 공통 헤더 분리
  36-COLLABORATION-iOS-CAMPUSPICK.xcodeproj/project.pbxproj
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Components/ClubHeaderView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Components/Enum/HeaderType.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Club/filter_icon.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Club/filter_icon.imageset/filter_icon.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/ViewController/ClubViewController.swift
Labels: Refactor 🏗️, 한열 🧄

#15 [Docs] #2 - 프로젝트 세팅
  36-COLLABORATION-iOS-CAMPUSPICK.xcodeproj/project.pbxproj
  36-COLLABORATION-iOS-CAMPUSPICK/Application/Info.plist
Labels: Docs 📑, 나연 🧸

#18 [Docs] #17 - 컨피그 생성..2
  36-COLLABORATION-iOS-CAMPUSPICK.xcodeproj/project.pbxproj
  36-COLLABORATION-iOS-CAMPUSPICK/Application/Info.plist
Labels: Docs 📑, 나연 🧸

#13 [Feat] #11 - Club Ranking Cell
  36-COLLABORATION-iOS-CAMPUSPICK.xcodeproj/project.pbxproj
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/Model/ClubRankingModel.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/View/Cell/ClubRankingCell.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/View/RankingView.swift
Labels: Feat 💻, 한열 🧄

#12 [Feat] #6 - 검색 UI
  36-COLLABORATION-iOS-CAMPUSPICK.xcodeproj/project.pbxproj
  36-COLLABORATION-iOS-CAMPUSPICK/Application/SceneDelegate.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Components/LeftAlignedCollectionViewFlowLayout.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Extensions/UIFont+.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/check_icon.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/check_icon.imageset/check.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/comment_icon.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/comment_icon.imageset/comment.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/view_icon.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/view_icon.imageset/view.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/x_icon.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/x_icon.imageset/icon.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/Model/Enum/DayType.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/Model/Enum/DeadlineType.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/Model/Enum/RegionType.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/Model/SearchModel.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/Cell/FilterCollectionViewCell.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/Cell/PopularSearchCollectionViewCell.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/Cell/RecentSearchCollectionViewCell.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/Cell/SearchTableViewCell.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/Cell/SortOptionTableViewCell.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/FilterView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/PopularSearchView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/RecentSearchView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/SearchCollectionViewCell.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/ViewController/SearchFilterModalViewController.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/ViewController/SearchResultViewController.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/ViewController/SearchSortModalViewController.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/ViewController/SearchViewController.swift
Labels: Feat 💻, 나연 🧸

#21 [Refactor] #19 - 검색 UI v2
  36-COLLABORATION-iOS-CAMPUSPICK.xcodeproj/project.pbxproj
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Components/ClubHeaderView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/Cell/SearchTableViewCell.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/ClubSortView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/ViewController/SearchResultViewController.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/ViewController/SearchViewController.swift
Labels: Refactor 🏗️, 나연 🧸

#26 [Network] #23 - 검색 네트워크 연결...
  36-COLLABORATION-iOS-CAMPUSPICK.xcodeproj/project.pbxproj
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Components/ClubHeaderView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_BLANK.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_BLANK.imageset/club_recruit_BLANK.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_COQUETIER.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_COQUETIER.imageset/club_recruit_COQUETIER.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_CRESOL.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_CRESOL.imageset/club_recruit_CRESOL.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_OVALKOREA.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_OVALKOREA.imageset/club_recruit_OVALKOREA.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_PLAYBOX.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_PLAYBOX.imageset/img_club2.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_TREMOLO.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_TREMOLO.imageset/club_recruit_TREMOLO.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_bethenose.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_bethenose.imageset/club_recruit_bethenose.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_foxstar.imageset/Contents.json
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Resources/Assets.xcassets/Search/club_recruit_foxstar.imageset/club_recruit_foxstar.svg
  36-COLLABORATION-iOS-CAMPUSPICK/Network/Club/ClubService.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Network/Club/Response/SearchClubResponseDTO.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/Model/Enum/DayType.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/Model/Enum/DeadlineType.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/Model/Enum/RegionType.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/Model/SearchModel.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/ClubSortView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/View/FilterView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/ViewController/SearchFilterModalViewController.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/ViewController/SearchResultViewController.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Search/ViewController/SearchViewController.swift
Labels: Network 📡, 나연 🧸

#28 [Feat] #24 - 마무으리!
  36-COLLABORATION-iOS-CAMPUSPICK/Global/Components/ClubHeaderView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/View/FindClubView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Club/ViewController/ClubViewController.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Home/VIewController/HomeViewController.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Home/View/MainIconView.swift
  36-COLLABORATION-iOS-CAMPUSPICK/Presentation/Home/View/PopularClubView.swift
Labels: Feat 💻, 한열 🧄

#30 [Docs] #29 - 리꾸(리드미꾸미기라는뜻)
  README.md
Labels: Docs 📑, 한열 🧄
